[package]
name = "paper-text"
description = "Typography model and shaping boundary for PaperOS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
cosmic-text.workspace = true
paper-display.workspace = true

[lints]
workspace = true
