[files]
extend-exclude = [
    "Cargo.lock",
    "apps/specimen/tests/golden/*.pgm",
    "artifacts/",
    "target/",
]

[default.extend-words]
bpp = "bpp"
GC16 = "GC16"
IT8951 = "IT8951"
M641 = "M641"
rustup = "rustup"
VCOM = "VCOM"
